apiVersion: v1
kind: Service
metadata:
  name: wyoming-whisper
  labels:
    app.kubernetes.io/name: wyoming-whisper
  annotations:
    metallb.io/address-pool: {{ .Values.service.metallbPool }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  selector:
    app.kubernetes.io/name: wyoming-whisper
  ports:
    - name: wyoming
      port: {{ .Values.service.port }}
      targetPort: wyoming
      protocol: TCP
